version: '3'
services:
  mysql:
    image: sergiuwat/mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    image: sergiuwat/connector_mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datasets
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root